### ISSUE TITLE
Reload config when it's been edited externally

### ISSUE THREAD

**Issue by bloctown** [titivermeesch/CommandTimer#127]
When managing config externally outside the game, then you update the timer json files, they're overwritten by game files. It would be useful to be able to edit these configs elsewhere, and then load them into the game so they arent overwritten

**Comment by titivermeesch** [comment]
@bloctown As for now, you can stop the server before uploading the new files again. You should also be able to upload the files by deactivating the timer first and then uploading the corresponding task file.

Does this solve your issue?
