### ISSUE TITLE
All commands are constantly spamming 15 times a seconds

### ISSUE THREAD

**Issue by Kachowster** [titivermeesch/CommandTimer#19]
I am trying to execute commands on certain days at certain times and all the commands are entered at once.

**Comment by titivermeesch** [comment]
Can you please show your configuration file

**Comment by Kachowster** [comment]
settings:
  tasks:
    '3':
      gender: console
      time:
      - '18:46:00'
      days:
      - SUNDAY
      commands:
      - title @a times 20 140 20
    '4':
      gender: console
      time:
      - '18:46:03'
      days:
      - SUNDAY
      commands:
      - title @a subtitle ["",{"text":"check ","color":"dark_red"},{"text":"#rules","color":"blue"},{"text":" for specifications","color":"dark_red"}]
    '5':
      gender: console
      time:
      - '19:00:00'
      days:
      - SUNDAY
      commands:
      - title @a title {"text":"Purge started","color":"red"}
    '6':
      gender: console
      time:
      - '18:30:00'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"30 mins","bold":true,"color":"light_purple"}]
    '7':
      gender: console
      time:
      - '18:45:00'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"15 mins","bold":true,"color":"light_purple"}]
   '8':
      gender: console
      time:
      - '18:55:00'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"5 mins","bold":true,"color":"light_purple"}]
    '9':
      gender: console
      time:
      - '18:59:00'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"1 min","bold":true,"color":"light_purple"}]
    '10':
      gender: console
      time:
      - '18:59:30'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"30 secs","bold":true,"color":"light_purple"}]
    '11':
      gender: console
      time:
      - '18:59:40'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"20 secs","bold":true,"color":"light_purple"}]
    '12':
      gender: console
      time:
      - '18:59:50'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"10 secs","bold":true,"color":"light_purple"}]
    '13':
      gender: console
      time:
      - '18:59:55'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"5 secs","bold":true,"color":"light_purple"}]
    '14':
      gender: console
      time:
      - '18:59:57'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"3 secs","bold":true,"color":"light_purple"}]
    '15':
      gender: console
      time:
      - '18:59:58'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"2 secs","bold":true,"color":"light_purple"}]
    '16':
      gender: console
      time:
      - '18:59:59'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will begin in ","color":"light_purple"},{"text":"1 sec","bold":true,"color":"light_purple"}]
    '17':
      gender: console
      time:
      - '19:30:00'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"30 mins","bold":true,"color":"light_purple"}]
    '18':
      gender: console
      time:
      - '19:45:00'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"15 mins","bold":true,"color":"light_purple"}]
    '19':
      gender: console
      time:
      - '19:55:00'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"5 mins","bold":true,"color":"light_purple"}]
    '20':
      gender: console
      time:
      - '19:59:00'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"1 min","bold":true,"color":"light_purple"}]
    '21':
      gender: console
      time:
      - '19:59:30'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"30 secs","bold":true,"color":"light_purple"}]
    '22':
      gender: console
      time:
      - '19:59:40'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"20 secs","bold":true,"color":"light_purple"}]
    '23':
      gender: console
      time:
      - '19:59:50'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"10 secs","bold":true,"color":"light_purple"}]
    '24':
      gender: console
      time:
      - '19:59:55'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"5 secs","bold":true,"color":"light_purple"}]
    '25':
      gender: console
      time:
      - '19:59:57'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"3 secs","bold":true,"color":"light_purple"}]
    '26':
      gender: console
      time:
      - '19:59:58'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"2 secs","bold":true,"color":"light_purple"}]
    '27':
      gender: console
      time:
      - '18:59:59'
      days:
      - SUNDAY
      commands:
      - tellraw @a ["",{"text":"[The Craft] ","color":"green"},{"text":"Purge","bold":true,"color":"dark_red"},{"text":" will end in ","color":"light_purple"},{"text":"1 sec","bold":true,"color":"light_purple"}]
    '30':
      gender: console
      time:
      - '19:46:00'
      days:
      - SUNDAY
      commands:
      - title @a times 20 140 20
    '31':
      gender: console
      time:
      - '19:46:03'
      days:
      - SUNDAY
      commands:
      - title @a subtitle {"text":"Hope you enjoyed your release of anger!","color":"aqua"}
    '32':
      gender: console
      time:
      - '20:00:00'
      days:
      - SUNDAY
      commands:
      - title @a title {"text":"Purge over","color":"green"}
    '33':
      gender: console
      time:
      - '09:05:00'
      days:
      - WEDNESDAY
      commands:
      - title @a title {"text":"Testing 123","color":"green"}


________________________________

**Comment by titivermeesch** [comment]
Please read the wiki and see how you use ontime and onday
