### ISSUE TITLE
spamming default commands

### ISSUE THREAD

**Issue by zooterxd** [titivermeesch/CommandTimer#20]
as soon as i restarted my plugin, the default commands came back in the GUI (despite not being in the config) and was then spamming every 10 seconds the 'this message appears every 10 seconds with a 50% chance'.

**Comment by titivermeesch** [comment]
Did you save the configuration file and reloaded the plugin? Please also use the latest version.
Please send me your configuration file and open a new issue. Without that I can't do anything

**Comment by MomaCods** [comment]
This is also happening on my server. I have uninstalled and reinstalled the .jar and deleted the command multiple times. 

I am using the latest version
I have restarted server 
I have saved configs from in game, in console and in the configs. 
I have reloaded the plugin and it just continues to spam chat with the message  'this message appears every 10 seconds with a 50% chance'.
