### ISSUE TITLE
Permissions system not working

### ISSUE THREAD

**Issue by MomaCods** [titivermeesch/CommandTimer#22]
I am sorry to open a ticket that seems to have been closed but... 

This is also happening on my server. I have uninstalled and reinstalled the .jar and deleted the command multiple times.

I am using the latest version
I have restarted server
I have saved configs from in game, in console and in the configs.
I have reloaded the plugin and it just continues to spam chat with the message 'this message appears every 10 seconds with a 50% chance'.

**Comment by MomaCods** [comment]
![commandspam](https://user-images.githubusercontent.com/17677132/65185429-87eba500-da35-11e9-8322-9594ffc36d9e.JPG)

**Comment by MomaCods** [comment]
![allcommandsdeleted](https://user-images.githubusercontent.com/17677132/65185453-92a63a00-da35-11e9-86bd-1cc6e5272cd1.JPG)

**Comment by MomaCods** [comment]
![configempty](https://user-images.githubusercontent.com/17677132/65185463-9a65de80-da35-11e9-9b31-08de02416e3d.JPG)

**Comment by MomaCods** [comment]
I have now readded what I want it to do.

**Comment by MomaCods** [comment]
![mycommands](https://user-images.githubusercontent.com/17677132/65186066-d3528300-da36-11e9-94cd-40aebeeac5ad.JPG)

**Comment by MomaCods** [comment]
![message came back](https://user-images.githubusercontent.com/17677132/65186139-0137c780-da37-11e9-9576-bf3c291f6a0f.JPG)

**Comment by MomaCods** [comment]
I have solved the issue (I think) it just stopped happening after a few restarts. 

I will keep you updated.

Sorry to bother :)

Also how might I get the plugin to whisper to the players? I would like a message to only them to say they have received their $ for 30 mins of playing time?

**Comment by titivermeesch** [comment]
Great that it is solved. I know that sometimes there can be some problems with the saving process and I'm working on a problem to fix that.
For the player thing, at the moment this is not possible but in the future there will be params like {player} to handle this kind of commands.

**Comment by MomaCods** [comment]
hi again. So new issue...

**Comment by MomaCods** [comment]
permission nodes doesn't seem to matter. I am currently Deoped and in a low low rank and I have the permission nodes set to each rank to recieve the money but isnt the plugin pays out all the money to me even though i only have 2 of the permission nodes

**Comment by MomaCods** [comment]
![paidfor all nodes](https://user-images.githubusercontent.com/17677132/65335073-ba121980-db91-11e9-95ae-412cdc598acb.JPG)

**Comment by MomaCods** [comment]
groups:
  survivor:
    default: true
    options:
      weight: '1000'
      rank: '1000'
      prefix: '&f[Survivor]&f<'
    permissions:
    - command.use.permission.100
    - coreprotect.inspect
    - quickshop.create.buy
    - quickshop.create.sell
    - quickshop.use
    - crazyenchantments.limit.3
    - armoredelytra.wear.diamond
    - e.permission
    - essentials.home.bed
    - essentials.backondeath
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.crates
    - essentials.warps.use
    - essentials.geoip.show
    - essentials.build.*
    - modifyworld.*
    - modifyworld.blocks.interact.*
    - essentials.help
    - essentials.helpop
    - essentials.motd
    - essentials.rules
    - essentials.signs.use.info
    - essentials.spawn
    - essentials.back.ondeath
    - essentials.bal
    - essentials.balance
    - essentials.balancetop
    - essentials.baltop
    - essentials.delhome
    - essentials.home
    - essentials.kit
    - essentials.kits.tools
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.pay
    - essentials.r
    - essentials.reply
    - essentials.sethome
    - essentials.tpdeny
    - essentials.tp.deny
    - essentials.signs.use
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.list
    - jobs.max.1
    - crazycrates.menu
    - xpbar.use
  Explorer:
    options:
      weight: '900'
      rank: '900'
      prefix: '&8[Explorer]&f<&8'
    permissions:
    - command.use.permission.150
    - command.use.permission.ex
    - a.permission
    - essentials.back
    - essentials.wb
    - essentials.workbench
    - essentials.kits.explorer
    - essentials.sethome.multiple
    - essentials.sethome.multiple.explorer
    - jobs.max.2
    inheritance:
    - survivor
  adventurer:
    options:
      weight: '800'
      rank: '800'
      prefix: '&7[Adventurer]&f<&7'
    permissions:
    - command.use.permission.200
    - s.permission
    - essentials.wb
    - essentials.workbench
    - essentials.ec
    - essentials.enderchest
    - essentials.kits.explorer
    - essentials.kits.adventurer
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.sethome.multiple.adventurer
    - jobs.max.3
    inheritance:
    - survivor
  settler:
    options:
      weight: '750'
      rank: '750'
      prefix: '&6[Settler]&f<&6'
    permissions:
    - command.use.permission.250
    - r.permission
    - essentials.afk
    - essentials.me
    - essentials.wb
    - essentials.workbench
    - essentials.ec
    - essentials.enderchest
    - essentials.kits.explorer
    - essentials.kits.adventurer
    - essentials.kits.settler
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.sethome.multiple.settler
    - jobs.max.4
    inheritance:
    - survivor
  reaper:
    options:
      weight: '700'
      rank: '700'
      prefix: '&5[Reaper]&f<&5'
    permissions:
    - command.use.permission.300
    - c.permission
    - essentials.afk
    - essentials.me
    - essentials.wb
    - essentials.workbench
    - essentials.ec
    - essentials.enderchest
    - essentials.kits.explorer
    - essentials.kits.adventurer
    - essentials.kits.settler
    - essentials.kits.reaper
    - essentials.fly
    - essentials.safefly
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.sethome.multiple.settler
    - jobs.max.5
    inheritance:
    - survivor
  carnivore:
    options:
      weight: '650'
      rank: '650'
      prefix: '&a[Carnivore]&f<&a'
    permissions:
    - command.use.permission.400
    - p.permission
    - worldedit.navigation.ascend
    - worldedit.navigation.descend
    - worldedit.navigation.thru.command
    - essentials.afk
    - essentials.me
    - essentials.wb
    - essentials.workbench
    - essentials.ec
    - essentials.enderchest
    - essentials.kits.explorer
    - essentials.kits.adventurer
    - essentials.kits.settler
    - essentials.kits.reaper
    - essentials.kits.carnivore
    - essentials.fly
    - essentials.safefly
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.sethome.multiple.carnivore
    - jobs.max.6
    inheritance:
    - survivor
    worlds: {}
  primal:
    options:
      weight: '600'
      rank: '600'
      prefix: '&b[PrimalSpirit]&f<&b'
    permissions:
    - command.use.permission.500
    - worldedit.navigation.ascend
    - worldedit.navigation.descend
    - worldedit.navigation.thru.command
    - essentials.afk
    - essentials.me
    - essentials.wb
    - essentials.workbench
    - essentials.ec
    - essentials.enderchest
    - essentials.kits.explorer
    - essentials.kits.adventurer
    - essentials.kits.settler
    - essentials.kits.reaper
    - essentials.kits.carnivore
    - essentials.fly
    - essentials.safefly
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.sethome.multiple.primal
    - jobs.max.7
    inheritance:
    - survivor

**Comment by MomaCods** [comment]
timeonload: true
settings:
  tasks:
    '1': {}
    '2':
      gender: console
      commands:
      - eco give * 100
      seconds: 1800
      useRandom: false
      permission: command.use.permission.100
    '3':
      gender: console
      commands:
      - eco give * 150
      seconds: 1800
      useRandom: false
      permission: command.use.permission.150
    '4':
      gender: console
      commands:
      - eco give * 200
      seconds: 1800
      useRandom: false
      permission: command.use.permission.200
    '5':
      gender: console
      commands:
      - eco give * 250
      seconds: 1800
      useRandom: false
      permission: command.use.permission.250
    '6':
      gender: console
      commands:
      - eco give * 300
      seconds: 1800
      useRandom: false
      permission: command.use.permission.300
    '7':
      gender: console
      commands:
      - eco give * 400
      seconds: 1800
      useRandom: false
      permission: command.use.permission.400
    '8':
      gender: console
      commands:
      - eco give * 500
      seconds: 1800
      useRandom: false
      permission: command.use.permission.500

**Comment by MomaCods** [comment]
https://pastebin.com/rDFyKZME

**Comment by MomaCods** [comment]
According to these settings I should only get 100 and 150

**Comment by MomaCods** [comment]
please help :)

**Comment by titivermeesch** [comment]
I'll have a look into this, it's very strange

**Comment by titivermeesch** [comment]
I see what you're trying to do, but this is not a permission issue. The problem here is that the command don't look after the player, it just gives x money to everyone. To let this work you'll need the {player} placeholder but it is not implemented yet. I'll try to implement it today

**Comment by MomaCods** [comment]
oh perfect! thank you I look forward to that. Seems it will fix both of my issues :) I appreciate your help on this matter

**Comment by MomaCods** [comment]
Any luck??

**Comment by titivermeesch** [comment]
Sorry I didn't have any time to work on it rn.

**Comment by titivermeesch** [comment]
I'm working on a kind of big update of the plug-in and it will be released in the near future but I can't say when it will be done

**Comment by MomaCods** [comment]
THis is my config setting.
I intend for different ranks to be given money every 30 mins while they are on line. But it is not running the commands. I have added the permission to each different rank so that only the amount per rank is given. but it still doesnt show up and I think I am having an issue with the random part I removed that section all together should I not have?




timeonload: true

  tasks:
    '1':
      gender: console
      commands:
      - eco give * 10
      seconds: 10
      permission: command.use.permission10
    '2':
      gender: console
      commands:
      - eco give * 150
      seconds: 10
      random: 100
      permission: command.use.permission150
    '3':
      gender: console
      commands:
      - eco give * 200
      seconds: 10
      permission: command.use.permission200
    '4':
      gender: console
      commands:
      - eco give * 250
      seconds: 10
      permission: command.use.permission250
    '5':
      gender: console
      commands:
      - eco give * 300
      seconds: 10
      permission: command.use.permission300
    '6':
      gender: console
      commands:
      - eco give * 400
      seconds: 10
      permission: command.use.permission400
    '7':
      gender: console
      commands:
      - eco give * 500
      seconds: 10
      permission: command.use.permission500
    '8':
      gender: operator
      commands: '0'

**Comment by titivermeesch** [comment]
Let me have a look at the permissions system and see if there is anything wrong there

**Comment by titivermeesch** [comment]
I just figured out that the way you implemented permissions is not the way it was meant to work. The permission value was actually used when gender is player, and the command would only get executed by the player if he had that permission.

I'll see what I can do to let it work with the console gender as well.

**Comment by MomaCods** [comment]
thank you.

the player definitely dont have the perms to pay themselves lol

hopefully you are able to help me :) I appreciate it

**Comment by titivermeesch** [comment]
Should be fixed in 3.0.2

**Comment by MomaCods** [comment]
Oh man! You are the best! Im implementing it now... I will let you know how
I fair!

**Comment by MomaCods** [comment]
[image: op not op.JPG]
the pic show that when I am not OP it is running the command like the
player is trying to run it.
this is the current config

https://pastebin.com/iKGwA3Er

**Comment by MomaCods** [comment]
The red circle is while I was op the blue I was deop and it is running it
like the player is do it. not console

**Comment by titivermeesch** [comment]
First of all don't use quotes around your command and don't use the number 1 as a command name, there are some issues with it (if you put "1").

For the other issue, my fault. Pretty dumb that I didn't see that one...

**Comment by titivermeesch** [comment]
Fixed in 3.0.2.1, let me know if it's fixed for you as well

**Comment by MomaCods** [comment]
checking it now

**Comment by MomaCods** [comment]
Its fixed! Running exactly as i need! THank you so much!!!

**Comment by titivermeesch** [comment]
Awesome

**Comment by MomaCods** [comment]
ok so I was the only person on at the time of testing and it seemed like it
was bang on... now I have players on and its paying everyone
[image: Capture..JPG]

**Comment by MomaCods** [comment]
seems as though the placeholder isnt working

**Comment by MomaCods** [comment]
[image: C1.JPG]
[image: c2.JPG]

**Comment by MomaCods** [comment]
https://pastebin.com/wSrjv6u1

**Comment by titivermeesch** [comment]
Can you try another name for the command ? And I can't see the picture...

**Comment by MomaCods** [comment]
it seems the console will only run commands the player could run themselves
but the players cannot run /eco give the place holder {player} doesnt work
it cant find the player... am I using the placeholder incorrectly? I tried
doing it with a  * as well and it just runs it for everyone.

**Comment by MomaCods** [comment]
Im not sure what other command I might use that would mimic this as its the
only thing I really need it to do... pay each player every 30mins

**Comment by MomaCods** [comment]
I think if I can get the placeholder {player} or %player% or whatever it
might be.. it will do everything I need it to ... sorry to be a bother... I
really love the plugin...

**Comment by titivermeesch** [comment]
I'll look into it, the latest version has PAPI support so it may interfere with that now.

**Comment by MomaCods** [comment]
Thanks ... you are awesome!

**Comment by titivermeesch** [comment]
To come back on this issue, version 4.0 will be released soon with a lot of cool new features, and a fix for this is in it, the fix will be to use a player placeholder instead of using the *.

Here is one of your old tasks : 
`'1':
gender: console
commands:
- eco give * 10
seconds: 10
permission: command.use.permission10`

The correct replacement will be this (Along with the PlaceholderAPI installed on your side) : 
`'1':
gender: console
commands:
- eco give %player_name% 10
seconds: 10
permission: command.use.permission10`

You'll be notified on SpigotMC once the update is live.

**Comment by MomaCods** [comment]
Hi, I got the updated version and I add the stuff in the config and I do /commandtimer reload and it says there is an internal error. I took the new one out and put the older one back in and /commandtimer reload works fine ... so I am not able to see if it works at all... cuz even after a reboot of the entire server it seems that none of the commmands are being run at all.

**Comment by MomaCods** [comment]
i also ran it through a YAML parser to make sure I didnt have an issue in my YAML and it said its good

**Comment by titivermeesch** [comment]
Can you please check in the console if the plugin is complaining about an invalid configuration? It should say "Configuration valid" if everything is ok.

**Comment by MomaCods** [comment]
Looks like even thought the YAML parser liked it ... the config didnt. I have pulled all my configs and just run it as you have created now I am attempting to add my configs 1 at a time to ensure I get it right. I appreciate all your dedication to this and tthe plugin. Its an awesome plugin!

**Comment by titivermeesch** [comment]
Maybe paste a screenshot of your console log here, I'll be able to see what is wrong
