### ISSUE TITLE
Suggestion: Correct delay to take place BEFORE the command rather than AFTER

### ISSUE THREAD

**Issue by accLarson** [titivermeesch/CommandTimer#243]
Commands have a delay setting which adds a wait time AFTER the command. 
I would expect the delay to occur before the command, (delaying the command itself).

I discussed it in Discord with PlayBossWar and he agreed. 
Here's a link to that Discord conversation: [Discord Chat Link](https://discord.com/channels/439618742633103370/693074541815136327/1188602515382607892)

**Comment by titivermeesch** [comment]
After further thinking I won't consider this change for the near future. The delay applies to the current command and changing it to "AFTER" could bring as much confusion as there is with the current implementation.
In case this brings some drastic issues with the plugin behaviour this change may be reconsidered.

**Comment by accLarson** [comment]
No worries.
I think you may have misunderstood when reconsidering though.
The delay does not apply to the current command. It delays the next command.

For example:
`Command: /ping` with` Delay: 10 Seconds`
`Command: /say TEST` with `Delay: 30 seconds`

Would follow this execution:

> Immediately execute `/ping`
Wait 10 seconds
Execute `/say test`
Wait 30 seconds... for nothing

Not the common sense approach in my opinion.
I would expect the following:

> Wait 10 seconds
Execute `/ping`
Wait 30 seconds
Execute `/say test`

Either way, if you did misunderstand or not, the plugin is generally great although I've moved on to using my host's web panel scheduler.

**Comment by titivermeesch** [comment]
You're right, I indeed wrote it the other way around. Actually it does make sense. I'm always getting really confused when discussing this feature.
Maybe having a dedicated "block" would make more sense. Meaning you could add a "delay" block that pauses for a set interval which can be put wherever you want. This would make it way more explicit as a wait block would be visible in the list of commands.
What do you think of that?

**Comment by accLarson** [comment]
Yeah, I think a delay block of its own makes a lot of sense.
