### ISSUE TITLE
Show file when error on parse json

### ISSUE THREAD

**Issue by scorninpc** [titivermeesch/CommandTimer#245]
I cannot resolve this problem on my server

![image](https://github.com/titivermeesch/CommandTimer/assets/2607849/7ef15b0f-0425-47c3-bba9-e62f2af00ff2)

as the task dont exists anymore

![image](https://github.com/titivermeesch/CommandTimer/assets/2607849/5edcf073-8ff7-495f-90ab-9c2d9cea1305)

If the throw show file location, will be nice to resolve some problems

**Comment by titivermeesch** [comment]
The only file you have is `horaemhora.json` so I expect the issue to come from that file. An improvement can indeed be made to show the failing file.

**Comment by titivermeesch** [comment]
Actually now that I have a closer look, not sure if this is CommandTimer related. It's a Yaml parser that is failing, so nothing to do with the CMT json files

**Comment by scorninpc** [comment]
you are right! i put CommandTimer to execute command from ExcellentCrates, my fk bad! sorry
