### ISSUE TITLE
pls support 1.20.4

### ISSUE THREAD

**Issue by xiaoluofa** [titivermeesch/CommandTimer#249]
![image](https://github.com/titivermeesch/CommandTimer/assets/75927411/7c66f7d0-e15e-446a-853b-4a02581ecc55)

**Comment by titivermeesch** [comment]
Can you please provide some error logging around CommandTimer. CMT is running on 1.20.x for a while already without any issues.

**Comment by titivermeesch** [comment]
Going to close this since there is no real proof that things are broken on 1.20.4
