### ISSUE TITLE
Multiverse

### ISSUE THREAD

**Issue by iKorvath** [titivermeesch/CommandTimer#26]
I'm using this plugin to /fill an area and it is getting confused with the different worlds in Multiverse and saying the area is too large please give an option to chose the world the command is run in.

**Comment by titivermeesch** [comment]
Hi there,

If the command supports a world in it's parameters, for example /fill world_nether 0 0 0 .... Then I can implement it. If the command don't support a world parameter it will get a lot more difficult, but I'll look into it and alert you when I have a fix for this.

**Comment by titivermeesch** [comment]
This won't be fixed since this is a Minecraft issue that don't support multi world for certain commands.
