### ISSUE TITLE
Suggestion: Chinese version of the doc

### ISSUE THREAD

**Issue by SnowCutieOwO** [titivermeesch/CommandTimer#261]
As described in title, actually I was done of this a year ago and put it in a website of Minecraft, since that closed I moved all of them to github, you could view the full translated document here: https://snowcutieowo.github.io/CommandTimer
;)

Ah you don't need to do anything, i just post here to mention you that there's a such version of wiki could be used by users XD
(Also I will check your commits by routine to ensure stuffs of doc are up to date. Thanks!)

**Comment by titivermeesch** [comment]
Really happy to see that this actually exists. If you would like to add the documentation here as well feel free to do so. A PR with the translations and language setup is very welcome

**Comment by SnowCutieOwO** [comment]
> Really happy to see that this actually exists. If you would like to add the documentation here as well feel free to do so. A PR with the translations and language setup is very welcome

Since I'm running a project to put all plugins' wiki together, I used a standalone wiki platform (Docsify) and migrating wikis will be a lot of work which obviously not what I should do now (I still have a lot of wikis to translate :/)
