### ISSUE TITLE
Is this possible with this plugin?

### ISSUE THREAD

**Issue by FaultyFunctions** [titivermeesch/CommandTimer#278]
When player enters a world, set a timer for 30 minutes, timer will only count down if they are in the world otherwise it pauses if they leave the world and resumes when they return. After 30 minutes is up, teleport the player out of the world.

Would all of this be possible with this plugin?

**Comment by titivermeesch** [comment]
There is already an extension that checks player time in a world here: https://www.spigotmc.org/resources/player-conditions-commandtimer-extension.97186/
The issue with this is that it will reset the timer when the server restarts, when the user leaves the server or when the user switches worlds.
This is a very specific usecase so I would consider creating your own extension for this
