### ISSUE TITLE
Allow Per Tick Command Tasks

### ISSUE THREAD

**Issue by XCraftTM** [titivermeesch/CommandTimer#290]
I would like a Command to be runned each Minecraft Game Tick, is that possible to do?

**Comment by XCraftTM** [comment]
I want to run a Command Each Tick to modify all Entities properties...

**Comment by titivermeesch** [comment]
This seems like something that would be a better fit inside a custom plugin. Allowing CommandTimer to run on every tick has serious performance implications and would probably start lagging the server pretty much instantly.
What exactly do you want to modify? Could you maybe rely on an event that triggers to update the entity properties? For example an entity spawn event? If that's the case CommandTimer can hook into that and do some actions when an entity spawns
