### ISSUE TITLE
Configuration validation

### ISSUE THREAD

**Issue by s-kerdel** [titivermeesch/CommandTimer#39]
Hello,

Yesterday I tried to add Command Timer to a Spigot server, which seem to be promising.
Sadly I encounter the following error, is there something that needs to be changed in this plugin to make it work correctly?

![exception](https://user-images.githubusercontent.com/49479846/77627162-bf885c00-6f46-11ea-8f6a-d33234534f54.png)

Thanks in advance.

**Comment by titivermeesch** [comment]
Hi there,

It seems like you are missing the gender element in one of your tasks. I'll make an update to check that the config.yml file is valid.

More information about genders can be found here : https://github.com/titivermeesch/CommandTimer/wiki/Configuration-file

**Comment by s-kerdel** [comment]
Hello,

Thanks for the quick response!

As I just downloaded the plugin, the first run will provide this error since (as you point out) the default configuration seems to be incorrect.

Thanks to your comment I was pointed in the right direction, it seems the default configuration is missing the 'gender: console' at the bottom of the file to complete the ' world limited command' example.

Since you changed this report to configuration validation, I will keep this question/issue open 👍.

**Comment by titivermeesch** [comment]
Are you sure that it is missing? This is the config.yml that is default, or at least it should:
`#GENERAL
timeonload: true

tasks:
  command 1:
    commands:
      - say This message will only show up at a specific time.
    time:
      - 13:49
    gender: player
  random test command:
    commands:
      - say This message appears every 10 seconds with a chance of 50%
    seconds: 10
    gender: console
    random: 0.5
    perUser: true
  world limited command:
    gender: console
    commands:
      - say This command will only run on the main world and on Monday, Wednesday and Sunday
      - say This command will be executed sometimes as well
    seconds: 5
    days:
      - MONDAY
      - WEDNESDAY
      - SUNDAY
    worlds:
      - world
`

Is this different on your side?

**Comment by titivermeesch** [comment]
I made a hotfix on v4.0.1 regarding that configuration file issue, it seems like it don't like when console is on the first line of the task. I'll do a bigger update to fix that config validation and

**Comment by s-kerdel** [comment]
Hi there,

The default configuration CommandTimer is generating, is as follows (for me):

```#GENERAL
timeonload: true

tasks:
  command 1:
    commands:
      - say This message will only show up at a specific time.
    time:
      - 13:49
    gender: console
  random test command:
    commands:
      - say This message appears every 10 seconds with a chance of 50%
    seconds: 10
    gender: console
    random: 0.5
    perUser: true
  world limited command:
    commands:
      - say This command will only run on the main world and on Monday, Wednesday and Sunday
      - say This command will be executed sometimes as well
    seconds: 5
    days:
      - MONDAY
      - WEDNESDAY
      - SUNDAY
    worlds:
      - world
```

**Comment by s-kerdel** [comment]
As you might notice, the following things differ:

![image](https://user-images.githubusercontent.com/49479846/77642823-9247a800-6f5e-11ea-97fe-278d469d1c7c.png)

**Comment by titivermeesch** [comment]
In the last change I move the gender to a different place in the task, can you check by downloading the latest plugin and see if that resolves the issue?

**Comment by s-kerdel** [comment]
I reviewed your hotfix which indeed added the missing code and I've tested it on my server.

The default configuration is now fixed and doesn't throw null pointer exceptions anymore :).

Thanks for your quick responses and taking the effort.

**Comment by titivermeesch** [comment]
I'm still confused why this works and not in the previous config. The order shouldn't matter.
