### ISSUE TITLE
BungeeCord Support

### ISSUE THREAD

**Issue by Drc-DEV** [titivermeesch/CommandTimer#4]
Hi, I would find it really useful to have a BungeeCord compatible version of CommandTimer, it does not need any fancy gui or anything like that, even just the same config file and just a reload command would be 100% the coolest thing ever.

Another thing, can you re-add the reload command on CommandTimer for Spigot? Sometimes I want to update the configuration but I can't from console, due to the new GUI system. Thanks

**Comment by titivermeesch** [comment]
Hi,

Bungeecord version is already work in progress.
For the reload command I will re-add it in the next update, with maybe an alias like /ctr to make life easier.

Thanks for your suggestions

**Comment by Drc-DEV** [comment]
Any news on bungeecord support? It would be the only plugin that offers timed commands in bungeecord.

**Comment by titivermeesch** [comment]
Not yet, I've worked a little on this but it's far from ready. I'll let you know once it's ready.
Maybe if I say to myself that I'm doing this today it will be done 😄

**Comment by Drc-DEV** [comment]
I hope you get this done soon as there's no other plugin that can do that. <3
