### ISSUE TITLE
Unable to get timed commands to work.

### ISSUE THREAD

**Issue by s-kerdel** [titivermeesch/CommandTimer#40]
After some trial-error I've encountered several issues which make it impossible to setup the tasks I want.
For example, the following configuration is never executed, while using seconds instead of time does:
```
#GENERAL
timeonload: true

tasks:
  command:
    commands:
      - say This command is triggered.
    time:
      - 14:04:50
    gender: console
```

I've tried multiple time formats, 14:05, in-game time, with and without days, with timeonload to true and false.

---
Another weird issue I encountered was a command never being triggered due to having a separate number in the name (like the default configuration).

As example,
```
tasks:
  command 1:
```
Is never executed, while `command:` and `command test:` do.

**Comment by titivermeesch** [comment]
For the time issue, timeonload will just log the server time on server start, did the time you filled in correspond to the time zone your server is using? This can be seen when timeonload is true in the server console.

**Comment by titivermeesch** [comment]
For the other issue, I already encoutered that too, I forgot to create a ticket about it. I'll make an extra issue for that one

**Comment by titivermeesch** [comment]
For the time can you try and write the time like "14:00:00" with the brackets?

**Comment by titivermeesch** [comment]
Config file will have default time set with brackets. Wait until release v4.1 to get it fixed.
