### ISSUE TITLE
4.0.1 so two versions ago, works great and the two other updates disable the plugin.

### ISSUE THREAD

**Issue by Fonzee9** [titivermeesch/CommandTimer#47]
Error on 4.1 and 4.2: https://pastebin.com/baqvJ1TU

**Comment by titivermeesch** [comment]
Can you please share your configuration file? This seems pretty weird.

**Comment by titivermeesch** [comment]
And your full server log as well.

**Comment by Fonzee9** [comment]
Config: https://pastebin.com/mVKgWUbz

Startup error: https://pastebin.com/70ZWxi0v

**Comment by s-kerdel** [comment]
@Fonzee9 could you try this?

```
#GENERAL
timeonload: true

tasks:
  daily_reload:
    commands:
      - nm reload
    time:
      - "13:49:00"
    gender: console
  random_20s_reload:
    commands:
      - nm reload
    seconds: 20
    gender: console
    random: 0.5
```

There seemed to be odd stuff happening to configurations with separate numbers in their name. This might be a result of not using quoted command names @titivermeesch ?

Please let me know if this adjusted configuration works for you.

**Comment by titivermeesch** [comment]
There were always some issues with numbers and I didn't figure it out yet, so right now don't use them. I might came up with a fix.

**Comment by Fonzee9** [comment]
@s-kerdel that works on the latest version 4.2, thank you!!
