### ISSUE TITLE
Integrate plugin metrics

### ISSUE THREAD

**Issue by titivermeesch** [titivermeesch/CommandTimer#53]

**Comment by titivermeesch** [comment]
Can't really figure out why this is not working. Metrics is loaded but does not come in McStats

**Comment by ludgart** [comment]
Hello,

you can try to use bStats.

Regards
ludgart

**Comment by titivermeesch** [comment]
Thanks for that, I'll have a look into it.

**Comment by titivermeesch** [comment]
bStats will be in v5.2, but not sure if it actually works. I enabled debugging in bStats but no logging at all

**Comment by titivermeesch** [comment]
Included in **v5.2**
