### ISSUE TITLE
Internal Error Configuration

### ISSUE THREAD

**Issue by Salkim123** [titivermeesch/CommandTimer#56]
Here is my Configuration with the internal error :
#GENERAL
timeonload: true

tasks:
  random_test_command:
    commands:
      - tellraw @a {"text":"§6§l(EmeronMc)§a Mit §e'/inform'§a erfährst du alle §dwichtigen §9Funktionen §ades Servers! §aGlaub mir und §aschau vorbei!"}
    seconds: 880
    gender: console
    random: 0.8
    perUser: true
  Casino:
    commands:
      - tellraw @a {"text":"§6§l(EmeronMc) §aDu weißt nicht wie du dein Geld los werden sollst? §aBesuche unser §eCasino§r§a mit §5'/warp Casino'§a."}
    seconds: 690
    gender: console
    random: 0.5
    perUser: true
  Shop:
    commands:
      - tellraw @a {"text":"§6§l(EmeronMc) §aMöchtest du §eItems§a kaufen oder verkaufen? §aTippe §b'/warp Shop'§a in den Chat."}
    seconds: 765
    gender: console
    random: 1.0
    perUser: true
  Discord:
    commands:
      - tellraw @a {"text":"§eJoine auf unserem Discord! §7(§bhttps://discord.gg/rRaNFby§7)"}
    seconds: 700
    gender: console
    random: 0.6
    perUser: true
  Item-Clear5:
    commands:
      - tellraw @a {"text":"§aAlle Items, die auf dem Boden liegen, wurden entfernt!"}
      - minecraft:kill @e[type=minecraft:item]
    seconds: 910
    gender: console
    random: 1.0
    perUser: true
  Ban-Spieler:
    commands:
      - banip NotUnusual
      - banip IchBinOnlineDE
    seconds: 60
    gender: console
    random: 1.0
    perUser: true

Where is the Mistake?
The Lines are not at the same Location as when i edit this comment. Can i please conact you on Discord for this?

**Comment by titivermeesch** [comment]
You can contact me on my spigot server. I'll close this so that we can discuss this further there. https://discord.gg/3DUPq3y
