### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by AbelMG** [titivermeesch/CommandTimer#6]
Could you add placeholderapi support? I mean, for example, if the answer of the placeholder %askyblock_has_island% for a player is "no", then send him a title saying "&cUse /is start" every second, you know?
With answer I mean output...

**Comment by titivermeesch** [comment]
Hi there,

This is always on the to-do list : 
https://github.com/titivermeesch/CommandTimer/projects

It may take some time since I'm figuring out how to do this.
