### ISSUE TITLE
Plugin disabled

### ISSUE THREAD

**Issue by Crux-Ansata** [titivermeesch/CommandTimer#62]
Hello!
I have updated Commandtimer to the latest version, but I'm still getting the next messages in console:
16.07 09:02:31 [Server] ERROR null
16.07 09:02:31 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'cmt' in plugin CommandTimer v4.3.1 - plugin is disabled.

The plugin has never worked for us, unfortunately. Could you tell me how to fix this?
We're using the latest paper version (91)

**Comment by titivermeesch** [comment]
Can you please show your full server logs
