### ISSUE TITLE
More detailed PAPI placeholders

### ISSUE THREAD

**Issue by titivermeesch** [titivermeesch/CommandTimer#70]
Right now there are only 2 different placeholders.

We could add different placeholders for the data we have about that timer.

**Comment by ludgart** [comment]
I would be better if you can add support for all PAPI placeholders + conditionals for creating unique timers.

Regards
ludgart

**Comment by titivermeesch** [comment]
@ludgart CT supports all the PAPI placeholders, this ticket is about the placeholders CT injects into PAPI (So for example the placeholders about the last task execution)

For the conditions you can create a new ticket

**Comment by titivermeesch** [comment]
Included in **v5.2**
