### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by titivermeesch** [titivermeesch/CommandTimer#71]
Be able to save the timers in SQL to sync timers between multiple servers

**Comment by titivermeesch** [comment]
Ongoing discovery. Will be included in a beta release Q2 2024

**Comment by Zarkness** [comment]
hello, any news about this feature?

**Comment by titivermeesch** [comment]
@Zarkness Unfortunately no. Some work is already done but it's far from finished right now

**Comment by Zarkness** [comment]
ok, thank you very much I could really use this feature

**Comment by titivermeesch** [comment]
@Zarkness there will be a build available soon with database support. I would love your feedback on this. The idea is to launch it as a test first
