### ISSUE TITLE
Timer not executing at specific real life times

### ISSUE THREAD

**Issue by DereC4** [titivermeesch/CommandTimer#88]
hello, I've made a timer with a simple /tellraw command

If i use the increments (every 60 seconds) it executes just fine but once I switch to times (11:25:00) it stops executing at those times, even when I set it to a time for debug purposes (for example, it was 12:45 PM so I set it to 12:48 but at that time nothing executed)

The permissions are working but I'm not sure why it is not executing

**Comment by titivermeesch** [comment]
Is the server time corresponding to what you are basing your time on? You should see that on server startup

**Comment by titivermeesch** [comment]
Closing due to lack of information
